version: '3'
services:

  web:
    build: ./puzzle_app
    ports:
     - "6543:6543"
    volumes:
     - ./puzzle_app:/code
    command: pserve --reload development.ini
    depends_on:
     - db

  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: puzzle_app

  initialise-db:
    build: ./puzzle_app
    command: python puzzle_app/scripts/initializedb.py development.ini
    volumes:
     - ./puzzle_app:/code
    depends_on:
     - db

  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=puzzle_app

  engine-api:
    build: ./puzzle_app
    command: celery worker --app puzzle_app.jobs --ini development.ini -Q puzzle_app
    volumes:
     - ./puzzle_app:/code
    depends_on:
      - db
      - rabbitmq
